variables:
  AWS_DEFAULT_REGION: ap-southeast-2
  AWS_REGION: ap-southeast-2
  AWS_ACCOUNT: 814504268053

before_script:
  - env
  - echo ${AWS_ACCESS_KEY_ID}
  - echo ${AWS_SECRET_ACCESS_KEY}
  - terraform --version
  - aws --version

stages:
  - plan
  - upload
  - apply

tfplan:
  retry: 2
  tags:
    - python
  stage: plan
  script:
    - make plan
  only:
    refs:
      - merge_request
      - master
  artifacts:
    name: tfplan
    paths:
      - plans/.tfplan
    reports:
      terraform: plans/plan.json

s3upload:
  retry: 2
  tags:
    - python
  stage: upload
  script:
    - make upload
  only:
    refs:
      - master

tfapply:
  retry: 2
  tags:
    - python
  stage: apply
  script:
    - make apply
  only:
    refs:
      - master
  environment:
    name: linode
    url: https://cloud.linode.com/search/?query=label:forward-proxy
  dependencies:
    - tfplan
  when: manual
