variables:
  TF_VAR_linode_token: $TF_VAR_linode_token
  AWS_ACCESS_KEY_ID: $TF_VAR_aws_access_key_id
  AWS_SECRET_ACCESS_KEY: $TF_VAR_aws_secret_access_key
  AWS_DEFAULT_REGION: ap-southeast-2
  AWS_REGION: ap-southeast-2
  AWS_ACCOUNT: 814504268053

before_script:
  - terraform --version
  - aws --version

stages:
  - plan
  - upload
  - apply

tfplan:
  retry: 2
  tags:
    - python
  stage: plan
  script:
    - make plan
  only:
    refs:
      - merge_request
      - master

upload:
  retry: 2
  tags:
    - python
  stage: upload
  script:
    - make upload
  only:
    refs:
      - master

tfapply:
  retry: 2
  tags:
    - python
  stage: apply
  script:
    - make apply
  only:
    refs:
      - master
