variables:
  AWS_REGION: ap-southeast-2
  AWS_ACCOUNT: 814504268053

before_script:
  - terraform --version
  - aws --version

stages:
  - plan
  - upload
  - apply

tfplan:
  retry: 2
  tags:
    - python
  stage: plan
  script:
    - make plan
  only:
    refs:
      - merge_request
      - main
  artifacts:
    name: tfplan
    paths:
      - plans/.tfplan
    reports:
      terraform: plans/tfplan.json

s3upload:
  retry: 2
  tags:
    - python
  stage: upload
  script:
    - make upload
  only:
    refs:
      - main

tfapply:
  retry: 2
  tags:
    - python
  stage: apply
  script:
    - make apply
  only:
    refs:
      - main
  environment:
    name: linode
    url: https://cloud.linode.com/search/?query=label:forward-proxy
    on_stop: tfdestroy
  dependencies:
    - tfplan
  when: manual

tfdestroy:
  retry: 2
  stage: apply
  variables:
    GIT_STRATEGY: none
  tags:
    - python
  script:
    - make destroy
  when: manual
  environment:
    name: linode
    action: stop
  artifacts:
    name: tfdestroy
    paths:
      - plans/.tfdestroy
    reports:
      terraform: plans/tfdestroy.json
